name: Deploy
on:
  push:
    branches:
      - master
      - develop

jobs:
  docker_push:
    name: Push to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/build-push-action@v1
        with:
          repository: ${{ github.repository }}
          tag_with_ref: true
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
