
name: Docker
on: [push]

jobs:
  docker_build_push:
    name: Docker Build and Push
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/build-push-action@v1
        with:
          repository: jswny/dotfiles
          tags: latest
          push: false
