name: Test and Deploy
on:
  push:
    branches:
      - master
      - develop

jobs:
  docker_build:
    name: Docker Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/build-push-action@v1
        with:
          repository: jswny/dotfiles
          tag_with_ref: true
