name: Vint
on: [push]

jobs:
  vint:
    name: Vint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3
        uses: actions/setup-python@v1
        with:
          python-version: '3.8'
      - name: Install Vint
        run: pip install vint
      - name: Run Vint
        run: vint nvim/*.vim
